# Generated by Django 3.2 on 2021-05-31 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='surname',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='isFarmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
