# Generated by Django 3.0.5 on 2020-04-24 10:59

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200422_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Manufacturer name', 'verbose_name_plural': 'Manufacturers name'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Characteristic', 'verbose_name_plural': 'Characteristics'},
        ),
        migrations.AlterModelOptions(
            name='characteristicname',
            options={'verbose_name': 'Characteristic name', 'verbose_name_plural': 'Characteristics names'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Multimedia file', 'verbose_name_plural': 'Multimedia files'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=catalog.models.get_category_image_filename, verbose_name='Upload image'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='image',
            field=models.ImageField(upload_to=catalog.models.get_image_filename, verbose_name='Upload file'),
        ),
    ]
