# Generated by Django 3.0.5 on 2020-04-25 08:57

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200424_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='characteristicname',
            options={'verbose_name': 'Наименование характеристики', 'verbose_name_plural': 'Наименования характеристик'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар/услуга', 'verbose_name_plural': 'Товары/услуги'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Наименование производителя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=catalog.models.get_category_image_filename, verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='characteristicname',
            name='characteristic',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование товара/услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Короткое описание'),
        ),
    ]
