# Generated by Django 3.0.5 on 2020-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200425_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, to='catalog.Category', verbose_name='Підкатегории'),
        ),
    ]
