# Generated by Django 3.0.5 on 2020-04-25 09:46

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200425_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='data',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryName', to='catalog.CharacteristicName', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.Product', verbose_name='Товар/услуга'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='image',
            field=models.ImageField(upload_to=catalog.models.get_image_filename, verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар/услуга'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=catalog.models.get_project_image_filename, verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название проекта'),
        ),
    ]
