# Generated by Django 3.0.5 on 2020-05-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200430_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
