# Generated by Django 3.0.5 on 2020-05-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова страницы товара (meta keywords)'),
        ),
    ]
