# Generated by Django 3.0.5 on 2020-05-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова страницы товара/услуги (meta keywords)'),
        ),
    ]
