# Generated by Django 3.0.5 on 2020-05-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_meta_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='image',
            new_name='url',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, null=True, verbose_name='Главная картинка товара/услуги'),
        ),
    ]
