# Generated by Django 3.0.5 on 2020-05-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200522_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='is_main',
        ),
    ]
