# Generated by Django 3.0.5 on 2020-05-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_mediafile_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mediafile', to='catalog.Mediafile', verbose_name='Основное изображение'),
        ),
    ]
