# Generated by Django 3.0.5 on 2020-05-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_mediafile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='url',
            new_name='file',
        ),
    ]
