# Generated by Django 3.0.8 on 2021-01-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200824_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=128, null=True, verbose_name='Наименование товара/услуги по-украински'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование товара/услуги по-русски'),
        ),
    ]
