# Generated by Django 3.0.8 on 2021-01-15 07:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20210114_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description_uk',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
    ]
