# Generated by Django 3.0.8 on 2021-01-15 07:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_full_description_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_description_uk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание по-украински'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=128, null=True, verbose_name='Наименование по-украински'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_uk',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название проекта по-украински'),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание по-русски'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование по-русски'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание по-русски'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description_uk',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание по-украински'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание по-русски'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название проекта по-русски'),
        ),
    ]
