# Generated by Django 3.0.8 on 2021-02-26 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210115_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBrand',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brandName_ru', models.CharField(max_length=100, verbose_name='Наименование производителя')),
                ('brandName_ua', models.CharField(max_length=100, verbose_name='Наименование производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='NCharacteristicName',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('characteristic_ru', models.CharField(max_length=100, verbose_name='Наименование')),
                ('characteristic_ua', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Наименование характеристики',
                'verbose_name_plural': 'Наименования характеристик',
            },
        ),
    ]
