# Generated by Django 3.0.8 on 2021-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_nbrand_ncharacteristicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbrand',
            name='brandName_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование производителя'),
        ),
        migrations.AlterField(
            model_name='nbrand',
            name='brandName_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование производителя'),
        ),
    ]
