# Generated by Django 3.0.8 on 2021-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210226_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncharacteristicname',
            name='characteristic_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ncharacteristicname',
            name='characteristic_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование'),
        ),
    ]
