# Generated by Django 3.0.8 on 2021-02-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20210226_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='nname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncategoryName', to='catalog.NCharacteristicName', verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='product',
            name='nbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.NBrand', verbose_name='Производитель'),
        ),
    ]
