# Generated by Django 3.0.8 on 2021-02-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20210226_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
