# Generated by Django 3.0.8 on 2021-02-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
