# Generated by Django 3.0.8 on 2021-02-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_delete_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NBrand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nbrand',
            new_name='brand',
        ),
    ]
