# Generated by Django 3.0.8 on 2021-02-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20210227_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='name',
        ),
    ]
