# Generated by Django 3.0.8 on 2021-02-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_characteristic_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacteristicName',
        ),
    ]
