# Generated by Django 3.0.8 on 2021-02-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_delete_characteristicname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NCharacteristicName',
            new_name='CharacteristicName',
        ),
        migrations.RenameField(
            model_name='characteristic',
            old_name='nname',
            new_name='name',
        ),
    ]
