# Generated by Django 3.0.8 on 2021-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20210227_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='data_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение по-русски'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='data_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение по-украински'),
        ),
    ]
